Repository sprint8team6/team-project1, pull requests merged in 2024-07, with the labels that each got.

#6 style(염정훈): 이달의 차트 페이지 UI 구현(#001)
  src/components/Button.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/MonthChart.jsx
  src/pages/ListPage/MonthChartTab.jsx
  src/pages/ListPage/MonthIdol.jsx
  src/pages/ListPage/MonthIdolImg.jsx
  src/pages/ListPage/MyCredit.jsx
Labels: bugfix, style

#5 feat(임귀태): 모달 팝업 및 데이터 연결 구현 (#4)
  config-overrides.js
  jsconfig.json
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/PopupModal.jsx
  src/components/Modal/VoteModal.jsx
  src/contexts/ModalContext.js
  src/hooks/useModal.js
  src/pages/ListPage/IdolCard.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/MyCredit.jsx
  src/styles/CommonStyles.js
Labels: feat, style

#13 chore(김준완): eslint airbnb ruleset apply(#002)
  --cache-location/_logs/2024-07-13T06_46_10_740Z-debug-0.log
  --cache-location/_update-notifier-last-checked
  .eslintrc.json
  .gitattributes
  airbnb-exception.text
  settings.json
  src/pages/MyPage/Components/FavoriteCandidates.jsx
  src/pages/MyPage/Components/MiniPhotoCard.jsx
  src/pages/MyPage/Components/MyFavorites.jsx
Labels: chore

#15 feat(염정훈): 리스트 페이지 반응형 작업(#14)
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/MonthIdolImg.jsx
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthChartTab.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/pages/ListPage/components/MonthIdolImage.jsx
  src/pages/ListPage/components/MyCredit.jsx
  src/pages/ListPage/components/TributeSupport.jsx
Labels: feat, refactor, style

#18 refactor(임귀태): ESLint 추가 예외 처리 및 리팩토링 (#16)
  .eslintrc.json
  .prettierrc.js
  config-overrides.js
  package-lock.json
  package.json
  src/App.js
  src/components/Header.jsx
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/ModalTopbar.jsx
  src/components/Modal/PopupModal.jsx
  src/components/Modal/VoteModal.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/pages/ListPage/components/MyCredit.jsx
  src/pages/ListPage/components/TributeSupport.jsx
  src/pages/MyPage/Components/CircularPhoto.jsx
  src/pages/MyPage/Components/FavoriteCandidates.jsx
  src/pages/MyPage/Components/MiniPhotoCard.jsx
  src/pages/MyPage/Components/MyFavorites.jsx
  src/pages/MyPage/MyPage.jsx
Labels: chore, refactor

#19 refactor(염정훈): eslint 에러 내용 수정(#17)
  src/components/Modal/ChargeModal.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/pages/ListPage/components/MyCredit.jsx
  src/styles/GlobalStyle.js
Labels: chore, refactor

#10 style(장혁수): 랜딩 페이지 반응형 디자인 수정(#9)
  package-lock.json
  package.json
  src/pages/LandingPage/LandingPage.jsx
  src/styles/GlobalStyle.js
Labels: style

#12 feat(임귀태): CirculaIdolImage 공용 컴포넌트 완성 (#11)
  src/components/Button.jsx
  src/components/CircularIdolImage.jsx
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/PopupModal.jsx
  src/components/Modal/VoteModal.jsx
  src/contexts/useModalContext.js
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/styles/CommonStyles.js
  src/styles/GlobalStyle.js
Labels: feat, style

#21 bugfix(임귀태): Rename Checked_True.svg to checked_true.svg
  src/assets/svg/checked_true.svg
Labels: bugfix

#23 refactor(염정훈): eslint 오류 수정(#003)
  .eslintrc.json
  package-lock.json
Labels: refactor

#24 feat(임귀태): 투표 모달 UI 완성 및 팝업 구현 (#7)
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/PopupModal.jsx
  src/components/Modal/VoteModal.jsx
  src/components/RadioButton.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/pages/ListPage/components/MyCredit.jsx
  src/styles/CommonStyles.js
  src/styles/GlobalStyle.js
Labels: feat, style

#27 chore(김준완): pr양식 내용 추가(#25)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#28 chore(김준완): airbnb 예외사항 명세 파일(airbnb-exception.txt)작성 및 설정값 조정(#3)
  .eslintrc.json
  .gitmessage
  airbnb-exception.text
Labels: docs, chore

#31 feat(염정훈): 리스트 페이지 후원을 기다리는 조공 캐러셀 기능 구현(#30)
  .vscode/settings.json
  package-lock.json
  package.json
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/TributeSupport.jsx
Labels: feat

#33 feat(임귀태): 모달 관련 공용 컴포넌트 추가 및 전체 모달에 적용 (#26)
  .eslintrc.json
  airbnb-exception.text
  package-lock.json
  package.json
  src/components/Button.jsx
  src/components/CircularIdolImage.jsx
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalTopbar.jsx
  src/components/Modal/PopupModal.jsx
  src/components/Modal/VoteModal.jsx
  src/components/RadioButton.jsx
  src/index.js
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/styles/CommonStyles.js
Labels: feat, refactor

#34 feat(염정훈): 리스트 페이지 이달의 차트 탭 기능 구현(#32)
  src/components/CircularIdolImage.jsx
  src/pages/ListPage/components/BoyChartList.jsx
  src/pages/ListPage/components/GirlChartList.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthChartTab.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/pages/ListPage/components/MonthIdolImage.jsx
  src/pages/ListPage/components/MyCredit.jsx
Labels: feat, refactor

#38 feat: idolApi 구현
  .gitignore
  package-lock.json
  package.json
  src/utils/dummyFile
  src/utils/idolApi.js
Labels: feat

#39 feat(염정훈): 리스트 페이지 내 크레딧 로컬 스토리지 구현(#37)
  src/components/CircularIdolImage.jsx
  src/pages/ListPage/components/MyCredit.jsx
Labels: feat, refactor

#41 feat(염정훈): useCreditContext.js 구현 (#40)
  src/contexts/useCreditContext.js
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/components/MyCredit.jsx
  src/utils/idolApi.js
Labels: feat, refactor

#42 feat(임귀태): Modal에서 Credit과 연동 (#40)
  src/components/CircularIdolImage.jsx
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/VoteModal.jsx
  src/contexts/useCreditContext.js
  src/contexts/useModalContext.js
  src/pages/ListPage/ListPage.jsx
Labels: feat, docs, refactor

#43 feat(김준완): mypage 반응형 및 UI작업 마무리(로컬 스토리지 및 기능 일부 포함)(#29)
  package-lock.json
  src/constants/dummyFile
  src/constants/globalConstant.js
  src/pages/MyPage/Components/CircularPhoto.jsx
  src/pages/MyPage/Components/FavoriteCandidates.jsx
  src/pages/MyPage/Components/MiniPhotoCard.jsx
  src/pages/MyPage/Components/MyFavorites.jsx
  src/pages/MyPage/MyPage.jsx
Labels: feat, test, style

#46 feat(염정훈): 리스트 페이지 후원을 기다리는 조공 api 연동 구현(#45)
  package.json
  src/apis/idolApi.js
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/TributeSupport.jsx
Labels: feat, refactor

#48 feat: VoteModal idolApi 연동, 로딩 UI 적용 (#47)
  package-lock.json
  package.json
  src/apis/dummyFile
  src/apis/idolApi.js
  src/components/Button.jsx
  src/components/CircularIdolImage.jsx
  src/components/LoadingSpinner.jsx
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalTopbar.jsx
  src/components/Modal/PopupModal.jsx
  src/components/Modal/VoteModal.jsx
  src/components/RadioButton.jsx
  src/pages/ListPage/components/MonthChart.jsx
Labels: feat, style

#50 feat(장혁수): 랜딩페이지 localstorage 초기화하는 버튼 추가(#49)
  package-lock.json
  src/pages/LandingPage/LandingPage.jsx
  src/pages/MyPage/Components/MiniPhotoCard.jsx
Labels: feat

#55 feat(임귀태): Toast 및 VoteModal UI 구현 (#47)
  src/components/LoadingSpinner.jsx
  src/components/Modal/ChargeModal.jsx
  src/components/Modal/DonationModal.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalTopbar.jsx
  src/components/Modal/PopupModal.jsx
  src/components/Modal/Toast.jsx
  src/components/Modal/VoteModal.jsx
  src/contexts/useToastContext.js
  src/pages/ListPage/ListPage.jsx
  src/styles/CommonStyles.js
Labels: feat, style

#56 feat(김준완): MyPage 기능 구현(#44)
  --cache-location/_logs/2024-07-18T08_06_54_845Z-debug-0.log
  .eslintrc.json
  .gitattributes
  airbnb-exception.text
  package-lock.json
  package.json
  src/pages/MyPage/Components/FavoriteCandidates.jsx
  src/pages/MyPage/Components/MiniPhotoCard.jsx
  src/pages/MyPage/Components/MyFavorites.jsx
  src/utils/idolApi.js
Labels: bugfix, feat, refactor

#57 feat(염정훈): 리스트 페이지(후원을 기다리는 조공, 이달의 차트) 기능 구현(#54)
  src/components/LoadingSpinner.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthChartList.jsx
  src/pages/ListPage/components/MonthChartTab.jsx
  src/pages/ListPage/components/TributeSupport.jsx
Labels: feat, refactor, style

#58 refactor(염정훈): import순서 변경&console 에러 수정(#54)
  package-lock.json
  package.json
  public/index.html
  src/apis/idolApi.js
  src/components/CircularIdolImage.jsx
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthChartList.jsx
  src/pages/ListPage/components/MonthChartTab.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/pages/ListPage/components/MyCredit.jsx
  src/pages/ListPage/components/TributeSupport.jsx
Labels: refactor

#59 feat(임귀태): DonationModal 후원 이후 IdolCard에 실시간 반영 (#47)
  package.json
  src/apis/idolApi.js
  src/components/Modal/DonationModal.jsx
  src/pages/ListPage/components/IdolCard.jsx
  src/pages/MyPage/Components/FavoriteCandidates.jsx
  src/pages/NotFoundPage/dummyFile
  src/utils/initializeLocalStorage.js
Labels: feat

#63 refactor(염정훈): 이달의 차트 더보기 버튼 클릭시 접기 버튼 노출 에러 수정(#62)
  src/pages/ListPage/components/MonthChart.jsx
Labels: refactor

#68 feat(김준완): MyPage 기능 구현 - 컴포넌트 간 데이터 연동(#44)
  package-lock.json
  package.json
  src/pages/MyPage/Components/FavoriteCandidates.jsx
  src/pages/MyPage/Components/MyFavorites.jsx
  src/pages/MyPage/MyPage.jsx
Labels: bugfix, feat

#70 feat(염정훈): 리스트 페이지 이달의 차트 더보기 버튼 기능 추가(#69)
  src/pages/ListPage/components/MonthChart.jsx
Labels: feat

#75 bugfix(염정훈): api 에러 수정(#74)
  netlify.toml
  package.json
  public/_redirects
  src/apis/idolApi.js
  src/pages/ListPage/components/MonthChart.jsx
  src/pages/ListPage/components/MonthChartList.jsx
  src/pages/ListPage/components/MonthIdol.jsx
  src/pages/ListPage/components/TributeSupport.jsx
Labels: bugfix, feat, refactor

#73 feat(임귀태): VoteModal 무한 스크롤 구현 (#60)
  src/components/Button.jsx
  src/components/LoadingSpinner.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/VoteModal.jsx
  src/styles/CommonStyles.js
Labels: feat

#78 feat(임귀태): 모달 버그 수정 및 기타 세부 기능 구현 (#60)
  src/components/LoadingSpinner.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/VoteModal.jsx
  src/pages/ListPage/components/MonthIdol.jsx
Labels: bugfix, feat, style

#77 feat: mypage 반응형 구현
  package.json
  src/pages/MyPage/Components/FavoriteCandidates.jsx
  src/pages/MyPage/Components/MyFavorites.jsx
  src/pages/MyPage/MyPage.jsx
Labels: feat, refactor, style

#79 docs: Update README.md
  README.md
Labels: docs

#80 style(김준완) : 추가하기 버튼 radius 설정(#29)
  src/components/Button.jsx
  src/pages/MyPage/Components/FavoriteCandidates.jsx
Labels: style

#81 docs: Update README.md
  README.md
Labels: docs
